version: '3.8'
services:
  player:
    container_name: player-container
    build: ./
    ports:
      - "8090:8090"
    depends_on:
      - player-DB
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://player-DB:5432/test
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123

  player-DB:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
